Transfer models
Dwolla/dwolla-v2-csharp pull request #12
Opened 2017-11-13 21:20 UTC by ithielnor

2017-11-14 03:36 UTC, therockstorm requested changes

2017-11-14 03:36 UTC, therockstorm commented on ExampleApp/DwollaBroker.cs
> +        public async Task<TransferResponse> GetTransferAsync(Uri uri) =>
This doesn't look like it's used

2017-11-14 15:40 UTC, ithielnor commented on ExampleApp/DwollaBroker.cs
> +        public async Task<TransferResponse> GetTransferAsync(Uri uri) =>
Removed

2017-11-15 00:59 UTC, therockstorm approved these changes

2017-11-15 00:59 UTC, merged