Funding Source Balance Model
Dwolla/dwolla-v2-csharp pull request #9
Opened 2017-11-07 14:53 UTC by ithielnor

Built on #8

2017-11-08 19:42 UTC, therockstorm commented
Can you merge master into this?

2017-11-10 14:37 UTC, ithielnor commented
This has been updated.

2017-11-10 18:18 UTC, therockstorm requested changes

2017-11-10 18:18 UTC, therockstorm commented on Dwolla.Client/Models/Responses/BalanceResponse.cs
> +    }
You had no way of knowing this, but in the next week or so this endpoint will be async and return immediately with an optional `string Status`. If Status="pending", Balance and LastUpdated will be null so you can change it to `DateTime?` and add the Status if you'd like.

2017-11-10 18:18 UTC, therockstorm commented on Dwolla.Client/Models/Responses/BalanceResponse.cs
> +    public class Balance
This is used by other endpoints so a more generic name would be better. We call it `Money` in our server code.

2017-11-10 19:01 UTC, ithielnor commented
Completed.

2017-11-10 19:03 UTC, ithielnor commented
I'm gonna close this and combine with #10 to avoid a breaking change between the two. `Money` will be in the Models namespace instead of the Responses.

2017-11-10 19:03 UTC, closed without merging